// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockpathUtils is a mock of pathUtils interface.
type MockpathUtils struct {
	ctrl     *gomock.Controller
	recorder *MockpathUtilsMockRecorder
	isgomock struct{}
}

// MockpathUtilsMockRecorder is the mock recorder for MockpathUtils.
type MockpathUtilsMockRecorder struct {
	mock *MockpathUtils
}

// NewMockpathUtils creates a new mock instance.
func NewMockpathUtils(ctrl *gomock.Controller) *MockpathUtils {
	mock := &MockpathUtils{ctrl: ctrl}
	mock.recorder = &MockpathUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpathUtils) EXPECT() *MockpathUtilsMockRecorder {
	return m.recorder
}

// GetRelativePath mocks base method.
func (m *MockpathUtils) GetRelativePath(filePath, baseDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelativePath", filePath, baseDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativePath indicates an expected call of GetRelativePath.
func (mr *MockpathUtilsMockRecorder) GetRelativePath(filePath, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativePath", reflect.TypeOf((*MockpathUtils)(nil).GetRelativePath), filePath, baseDir)
}
