run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable:
      - shadow
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/yanodintsovmercuryo/cursor-rules-syncer
  
  golint:
    min-confidence: 0.8
  
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - goconst

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - errcheck
      text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    
    # Exclude linters in certain dirs
    - path: cmd/
      linters:
        - gocyclo 