// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockfileOps is a mock of fileOps interface.
type MockfileOps struct {
	ctrl     *gomock.Controller
	recorder *MockfileOpsMockRecorder
	isgomock struct{}
}

// MockfileOpsMockRecorder is the mock recorder for MockfileOps.
type MockfileOpsMockRecorder struct {
	mock *MockfileOps
}

// NewMockfileOps creates a new mock instance.
func NewMockfileOps(ctrl *gomock.Controller) *MockfileOps {
	mock := &MockfileOps{ctrl: ctrl}
	mock.recorder = &MockfileOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileOps) EXPECT() *MockfileOpsMockRecorder {
	return m.recorder
}

// CopyFile mocks base method.
func (m *MockfileOps) CopyFile(srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockfileOpsMockRecorder) CopyFile(srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockfileOps)(nil).CopyFile), srcPath, dstPath)
}

// FileExists mocks base method.
func (m *MockfileOps) FileExists(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockfileOpsMockRecorder) FileExists(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockfileOps)(nil).FileExists), filePath)
}

// ReadFileNormalized mocks base method.
func (m *MockfileOps) ReadFileNormalized(filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNormalized", filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNormalized indicates an expected call of ReadFileNormalized.
func (mr *MockfileOpsMockRecorder) ReadFileNormalized(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNormalized", reflect.TypeOf((*MockfileOps)(nil).ReadFileNormalized), filePath)
}

// WriteFile mocks base method.
func (m *MockfileOps) WriteFile(filePath, content string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filePath, content, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockfileOpsMockRecorder) WriteFile(filePath, content, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockfileOps)(nil).WriteFile), filePath, content, perm)
}

// MockheaderService is a mock of headerService interface.
type MockheaderService struct {
	ctrl     *gomock.Controller
	recorder *MockheaderServiceMockRecorder
	isgomock struct{}
}

// MockheaderServiceMockRecorder is the mock recorder for MockheaderService.
type MockheaderServiceMockRecorder struct {
	mock *MockheaderService
}

// NewMockheaderService creates a new mock instance.
func NewMockheaderService(ctrl *gomock.Controller) *MockheaderService {
	mock := &MockheaderService{ctrl: ctrl}
	mock.recorder = &MockheaderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockheaderService) EXPECT() *MockheaderServiceMockRecorder {
	return m.recorder
}

// ExtractHeaderFromContent mocks base method.
func (m *MockheaderService) ExtractHeaderFromContent(content string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractHeaderFromContent", content)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractHeaderFromContent indicates an expected call of ExtractHeaderFromContent.
func (mr *MockheaderServiceMockRecorder) ExtractHeaderFromContent(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractHeaderFromContent", reflect.TypeOf((*MockheaderService)(nil).ExtractHeaderFromContent), content)
}

// RemoveHeaderFromContent mocks base method.
func (m *MockheaderService) RemoveHeaderFromContent(content string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHeaderFromContent", content)
	ret0, _ := ret[0].(string)
	return ret0
}

// RemoveHeaderFromContent indicates an expected call of RemoveHeaderFromContent.
func (mr *MockheaderServiceMockRecorder) RemoveHeaderFromContent(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHeaderFromContent", reflect.TypeOf((*MockheaderService)(nil).RemoveHeaderFromContent), content)
}
