// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockoutputService is a mock of outputService interface.
type MockoutputService struct {
	ctrl     *gomock.Controller
	recorder *MockoutputServiceMockRecorder
	isgomock struct{}
}

// MockoutputServiceMockRecorder is the mock recorder for MockoutputService.
type MockoutputServiceMockRecorder struct {
	mock *MockoutputService
}

// NewMockoutputService creates a new mock instance.
func NewMockoutputService(ctrl *gomock.Controller) *MockoutputService {
	mock := &MockoutputService{ctrl: ctrl}
	mock.recorder = &MockoutputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutputService) EXPECT() *MockoutputServiceMockRecorder {
	return m.recorder
}

// PrintErrorf mocks base method.
func (m *MockoutputService) PrintErrorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PrintErrorf", varargs...)
}

// PrintErrorf indicates an expected call of PrintErrorf.
func (mr *MockoutputServiceMockRecorder) PrintErrorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintErrorf", reflect.TypeOf((*MockoutputService)(nil).PrintErrorf), varargs...)
}

// PrintOperation mocks base method.
func (m *MockoutputService) PrintOperation(operationType, relativePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintOperation", operationType, relativePath)
}

// PrintOperation indicates an expected call of PrintOperation.
func (mr *MockoutputServiceMockRecorder) PrintOperation(operationType, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOperation", reflect.TypeOf((*MockoutputService)(nil).PrintOperation), operationType, relativePath)
}

// MockfileOps is a mock of fileOps interface.
type MockfileOps struct {
	ctrl     *gomock.Controller
	recorder *MockfileOpsMockRecorder
	isgomock struct{}
}

// MockfileOpsMockRecorder is the mock recorder for MockfileOps.
type MockfileOpsMockRecorder struct {
	mock *MockfileOps
}

// NewMockfileOps creates a new mock instance.
func NewMockfileOps(ctrl *gomock.Controller) *MockfileOps {
	mock := &MockfileOps{ctrl: ctrl}
	mock.recorder = &MockfileOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileOps) EXPECT() *MockfileOpsMockRecorder {
	return m.recorder
}

// CopyFile mocks base method.
func (m *MockfileOps) CopyFile(srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockfileOpsMockRecorder) CopyFile(srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockfileOps)(nil).CopyFile), srcPath, dstPath)
}

// FileExists mocks base method.
func (m *MockfileOps) FileExists(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockfileOpsMockRecorder) FileExists(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockfileOps)(nil).FileExists), filePath)
}

// FindAllFiles mocks base method.
func (m *MockfileOps) FindAllFiles(dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFiles", dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFiles indicates an expected call of FindAllFiles.
func (mr *MockfileOpsMockRecorder) FindAllFiles(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFiles", reflect.TypeOf((*MockfileOps)(nil).FindAllFiles), dir)
}

// ReadFileNormalized mocks base method.
func (m *MockfileOps) ReadFileNormalized(filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNormalized", filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNormalized indicates an expected call of ReadFileNormalized.
func (mr *MockfileOpsMockRecorder) ReadFileNormalized(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNormalized", reflect.TypeOf((*MockfileOps)(nil).ReadFileNormalized), filePath)
}

// RemoveFile mocks base method.
func (m *MockfileOps) RemoveFile(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockfileOpsMockRecorder) RemoveFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockfileOps)(nil).RemoveFile), filePath)
}

// WriteFile mocks base method.
func (m *MockfileOps) WriteFile(filePath, content string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filePath, content, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockfileOpsMockRecorder) WriteFile(filePath, content, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockfileOps)(nil).WriteFile), filePath, content, perm)
}

// MockpathUtils is a mock of pathUtils interface.
type MockpathUtils struct {
	ctrl     *gomock.Controller
	recorder *MockpathUtilsMockRecorder
	isgomock struct{}
}

// MockpathUtilsMockRecorder is the mock recorder for MockpathUtils.
type MockpathUtilsMockRecorder struct {
	mock *MockpathUtils
}

// NewMockpathUtils creates a new mock instance.
func NewMockpathUtils(ctrl *gomock.Controller) *MockpathUtils {
	mock := &MockpathUtils{ctrl: ctrl}
	mock.recorder = &MockpathUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpathUtils) EXPECT() *MockpathUtilsMockRecorder {
	return m.recorder
}

// GetBaseName mocks base method.
func (m *MockpathUtils) GetBaseName(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseName", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseName indicates an expected call of GetBaseName.
func (mr *MockpathUtilsMockRecorder) GetBaseName(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseName", reflect.TypeOf((*MockpathUtils)(nil).GetBaseName), filePath)
}

// GetDirectory mocks base method.
func (m *MockpathUtils) GetDirectory(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectory", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDirectory indicates an expected call of GetDirectory.
func (mr *MockpathUtilsMockRecorder) GetDirectory(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectory", reflect.TypeOf((*MockpathUtils)(nil).GetDirectory), filePath)
}

// GetRelativePath mocks base method.
func (m *MockpathUtils) GetRelativePath(filePath, baseDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelativePath", filePath, baseDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativePath indicates an expected call of GetRelativePath.
func (mr *MockpathUtilsMockRecorder) GetRelativePath(filePath, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativePath", reflect.TypeOf((*MockpathUtils)(nil).GetRelativePath), filePath, baseDir)
}

// NormalizePath mocks base method.
func (m *MockpathUtils) NormalizePath(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizePath", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// NormalizePath indicates an expected call of NormalizePath.
func (mr *MockpathUtilsMockRecorder) NormalizePath(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizePath", reflect.TypeOf((*MockpathUtils)(nil).NormalizePath), filePath)
}

// RecreateDirectoryStructure mocks base method.
func (m *MockpathUtils) RecreateDirectoryStructure(srcPath, srcBase, dstBase string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateDirectoryStructure", srcPath, srcBase, dstBase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecreateDirectoryStructure indicates an expected call of RecreateDirectoryStructure.
func (mr *MockpathUtilsMockRecorder) RecreateDirectoryStructure(srcPath, srcBase, dstBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateDirectoryStructure", reflect.TypeOf((*MockpathUtils)(nil).RecreateDirectoryStructure), srcPath, srcBase, dstBase)
}
