// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockfileOps is a mock of fileOps interface.
type MockfileOps struct {
	ctrl     *gomock.Controller
	recorder *MockfileOpsMockRecorder
	isgomock struct{}
}

// MockfileOpsMockRecorder is the mock recorder for MockfileOps.
type MockfileOpsMockRecorder struct {
	mock *MockfileOps
}

// NewMockfileOps creates a new mock instance.
func NewMockfileOps(ctrl *gomock.Controller) *MockfileOps {
	mock := &MockfileOps{ctrl: ctrl}
	mock.recorder = &MockfileOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileOps) EXPECT() *MockfileOpsMockRecorder {
	return m.recorder
}

// CopyFile mocks base method.
func (m *MockfileOps) CopyFile(srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockfileOpsMockRecorder) CopyFile(srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockfileOps)(nil).CopyFile), srcPath, dstPath)
}

// FileExists mocks base method.
func (m *MockfileOps) FileExists(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockfileOpsMockRecorder) FileExists(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockfileOps)(nil).FileExists), filePath)
}

// FindAllFiles mocks base method.
func (m *MockfileOps) FindAllFiles(dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFiles", dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFiles indicates an expected call of FindAllFiles.
func (mr *MockfileOpsMockRecorder) FindAllFiles(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFiles", reflect.TypeOf((*MockfileOps)(nil).FindAllFiles), dir)
}

// GetCurrentDir mocks base method.
func (m *MockfileOps) GetCurrentDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentDir indicates an expected call of GetCurrentDir.
func (mr *MockfileOpsMockRecorder) GetCurrentDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentDir", reflect.TypeOf((*MockfileOps)(nil).GetCurrentDir))
}

// MkdirAll mocks base method.
func (m *MockfileOps) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockfileOpsMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockfileOps)(nil).MkdirAll), path, perm)
}

// ReadFileNormalized mocks base method.
func (m *MockfileOps) ReadFileNormalized(filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNormalized", filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNormalized indicates an expected call of ReadFileNormalized.
func (mr *MockfileOpsMockRecorder) ReadFileNormalized(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNormalized", reflect.TypeOf((*MockfileOps)(nil).ReadFileNormalized), filePath)
}

// RemoveFile mocks base method.
func (m *MockfileOps) RemoveFile(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockfileOpsMockRecorder) RemoveFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockfileOps)(nil).RemoveFile), filePath)
}

// Stat mocks base method.
func (m *MockfileOps) Stat(filePath string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", filePath)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockfileOpsMockRecorder) Stat(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockfileOps)(nil).Stat), filePath)
}

// WriteFile mocks base method.
func (m *MockfileOps) WriteFile(filePath, content string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filePath, content, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockfileOpsMockRecorder) WriteFile(filePath, content, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockfileOps)(nil).WriteFile), filePath, content, perm)
}

// MockoutputService is a mock of outputService interface.
type MockoutputService struct {
	ctrl     *gomock.Controller
	recorder *MockoutputServiceMockRecorder
	isgomock struct{}
}

// MockoutputServiceMockRecorder is the mock recorder for MockoutputService.
type MockoutputServiceMockRecorder struct {
	mock *MockoutputService
}

// NewMockoutputService creates a new mock instance.
func NewMockoutputService(ctrl *gomock.Controller) *MockoutputService {
	mock := &MockoutputService{ctrl: ctrl}
	mock.recorder = &MockoutputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutputService) EXPECT() *MockoutputServiceMockRecorder {
	return m.recorder
}

// PrintErrorf mocks base method.
func (m *MockoutputService) PrintErrorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PrintErrorf", varargs...)
}

// PrintErrorf indicates an expected call of PrintErrorf.
func (mr *MockoutputServiceMockRecorder) PrintErrorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintErrorf", reflect.TypeOf((*MockoutputService)(nil).PrintErrorf), varargs...)
}

// PrintOperation mocks base method.
func (m *MockoutputService) PrintOperation(operationType, relativePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintOperation", operationType, relativePath)
}

// PrintOperation indicates an expected call of PrintOperation.
func (mr *MockoutputServiceMockRecorder) PrintOperation(operationType, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOperation", reflect.TypeOf((*MockoutputService)(nil).PrintOperation), operationType, relativePath)
}

// MockpathUtils is a mock of pathUtils interface.
type MockpathUtils struct {
	ctrl     *gomock.Controller
	recorder *MockpathUtilsMockRecorder
	isgomock struct{}
}

// MockpathUtilsMockRecorder is the mock recorder for MockpathUtils.
type MockpathUtilsMockRecorder struct {
	mock *MockpathUtils
}

// NewMockpathUtils creates a new mock instance.
func NewMockpathUtils(ctrl *gomock.Controller) *MockpathUtils {
	mock := &MockpathUtils{ctrl: ctrl}
	mock.recorder = &MockpathUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpathUtils) EXPECT() *MockpathUtilsMockRecorder {
	return m.recorder
}

// GetBaseName mocks base method.
func (m *MockpathUtils) GetBaseName(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseName", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseName indicates an expected call of GetBaseName.
func (mr *MockpathUtilsMockRecorder) GetBaseName(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseName", reflect.TypeOf((*MockpathUtils)(nil).GetBaseName), filePath)
}

// GetDirectory mocks base method.
func (m *MockpathUtils) GetDirectory(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectory", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDirectory indicates an expected call of GetDirectory.
func (mr *MockpathUtilsMockRecorder) GetDirectory(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectory", reflect.TypeOf((*MockpathUtils)(nil).GetDirectory), filePath)
}

// GetRelativePath mocks base method.
func (m *MockpathUtils) GetRelativePath(filePath, baseDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelativePath", filePath, baseDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativePath indicates an expected call of GetRelativePath.
func (mr *MockpathUtilsMockRecorder) GetRelativePath(filePath, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativePath", reflect.TypeOf((*MockpathUtils)(nil).GetRelativePath), filePath, baseDir)
}

// NormalizePath mocks base method.
func (m *MockpathUtils) NormalizePath(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizePath", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// NormalizePath indicates an expected call of NormalizePath.
func (mr *MockpathUtilsMockRecorder) NormalizePath(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizePath", reflect.TypeOf((*MockpathUtils)(nil).NormalizePath), filePath)
}

// RecreateDirectoryStructure mocks base method.
func (m *MockpathUtils) RecreateDirectoryStructure(srcPath, srcBase, dstBase string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateDirectoryStructure", srcPath, srcBase, dstBase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecreateDirectoryStructure indicates an expected call of RecreateDirectoryStructure.
func (mr *MockpathUtilsMockRecorder) RecreateDirectoryStructure(srcPath, srcBase, dstBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateDirectoryStructure", reflect.TypeOf((*MockpathUtils)(nil).RecreateDirectoryStructure), srcPath, srcBase, dstBase)
}

// MockcomparatorService is a mock of comparatorService interface.
type MockcomparatorService struct {
	ctrl     *gomock.Controller
	recorder *MockcomparatorServiceMockRecorder
	isgomock struct{}
}

// MockcomparatorServiceMockRecorder is the mock recorder for MockcomparatorService.
type MockcomparatorServiceMockRecorder struct {
	mock *MockcomparatorService
}

// NewMockcomparatorService creates a new mock instance.
func NewMockcomparatorService(ctrl *gomock.Controller) *MockcomparatorService {
	mock := &MockcomparatorService{ctrl: ctrl}
	mock.recorder = &MockcomparatorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcomparatorService) EXPECT() *MockcomparatorServiceMockRecorder {
	return m.recorder
}

// AreEqual mocks base method.
func (m *MockcomparatorService) AreEqual(file1, file2 string, overwriteHeaders bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreEqual", file1, file2, overwriteHeaders)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreEqual indicates an expected call of AreEqual.
func (mr *MockcomparatorServiceMockRecorder) AreEqual(file1, file2, overwriteHeaders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreEqual", reflect.TypeOf((*MockcomparatorService)(nil).AreEqual), file1, file2, overwriteHeaders)
}

// MockcopierService is a mock of copierService interface.
type MockcopierService struct {
	ctrl     *gomock.Controller
	recorder *MockcopierServiceMockRecorder
	isgomock struct{}
}

// MockcopierServiceMockRecorder is the mock recorder for MockcopierService.
type MockcopierServiceMockRecorder struct {
	mock *MockcopierService
}

// NewMockcopierService creates a new mock instance.
func NewMockcopierService(ctrl *gomock.Controller) *MockcopierService {
	mock := &MockcopierService{ctrl: ctrl}
	mock.recorder = &MockcopierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcopierService) EXPECT() *MockcopierServiceMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockcopierService) Copy(srcPath, dstPath string, overwriteHeaders bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", srcPath, dstPath, overwriteHeaders)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockcopierServiceMockRecorder) Copy(srcPath, dstPath, overwriteHeaders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockcopierService)(nil).Copy), srcPath, dstPath, overwriteHeaders)
}

// MockfilterService is a mock of filterService interface.
type MockfilterService struct {
	ctrl     *gomock.Controller
	recorder *MockfilterServiceMockRecorder
	isgomock struct{}
}

// MockfilterServiceMockRecorder is the mock recorder for MockfilterService.
type MockfilterServiceMockRecorder struct {
	mock *MockfilterService
}

// NewMockfilterService creates a new mock instance.
func NewMockfilterService(ctrl *gomock.Controller) *MockfilterService {
	mock := &MockfilterService{ctrl: ctrl}
	mock.recorder = &MockfilterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfilterService) EXPECT() *MockfilterServiceMockRecorder {
	return m.recorder
}

// CleanupExtraFilesByPatterns mocks base method.
func (m *MockfilterService) CleanupExtraFilesByPatterns(srcFiles []string, srcBase, dstBase string, patterns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExtraFilesByPatterns", srcFiles, srcBase, dstBase, patterns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExtraFilesByPatterns indicates an expected call of CleanupExtraFilesByPatterns.
func (mr *MockfilterServiceMockRecorder) CleanupExtraFilesByPatterns(srcFiles, srcBase, dstBase, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExtraFilesByPatterns", reflect.TypeOf((*MockfilterService)(nil).CleanupExtraFilesByPatterns), srcFiles, srcBase, dstBase, patterns)
}

// FindFilesByPatterns mocks base method.
func (m *MockfilterService) FindFilesByPatterns(dir string, patterns []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilesByPatterns", dir, patterns)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilesByPatterns indicates an expected call of FindFilesByPatterns.
func (mr *MockfilterServiceMockRecorder) FindFilesByPatterns(dir, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilesByPatterns", reflect.TypeOf((*MockfilterService)(nil).FindFilesByPatterns), dir, patterns)
}

// GetEffectivePatterns mocks base method.
func (m *MockfilterService) GetEffectivePatterns(patterns []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectivePatterns", patterns)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetEffectivePatterns indicates an expected call of GetEffectivePatterns.
func (mr *MockfilterServiceMockRecorder) GetEffectivePatterns(patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectivePatterns", reflect.TypeOf((*MockfilterService)(nil).GetEffectivePatterns), patterns)
}

// GetFilePatterns mocks base method.
func (m *MockfilterService) GetFilePatterns(flagValue, envVarName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePatterns", flagValue, envVarName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePatterns indicates an expected call of GetFilePatterns.
func (mr *MockfilterServiceMockRecorder) GetFilePatterns(flagValue, envVarName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePatterns", reflect.TypeOf((*MockfilterService)(nil).GetFilePatterns), flagValue, envVarName)
}
