// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockoutputService is a mock of outputService interface.
type MockoutputService struct {
	ctrl     *gomock.Controller
	recorder *MockoutputServiceMockRecorder
	isgomock struct{}
}

// MockoutputServiceMockRecorder is the mock recorder for MockoutputService.
type MockoutputServiceMockRecorder struct {
	mock *MockoutputService
}

// NewMockoutputService creates a new mock instance.
func NewMockoutputService(ctrl *gomock.Controller) *MockoutputService {
	mock := &MockoutputService{ctrl: ctrl}
	mock.recorder = &MockoutputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutputService) EXPECT() *MockoutputServiceMockRecorder {
	return m.recorder
}

// PrintErrorf mocks base method.
func (m *MockoutputService) PrintErrorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PrintErrorf", varargs...)
}

// PrintErrorf indicates an expected call of PrintErrorf.
func (mr *MockoutputServiceMockRecorder) PrintErrorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintErrorf", reflect.TypeOf((*MockoutputService)(nil).PrintErrorf), varargs...)
}
