// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockoutputService is a mock of outputService interface.
type MockoutputService struct {
	ctrl     *gomock.Controller
	recorder *MockoutputServiceMockRecorder
	isgomock struct{}
}

// MockoutputServiceMockRecorder is the mock recorder for MockoutputService.
type MockoutputServiceMockRecorder struct {
	mock *MockoutputService
}

// NewMockoutputService creates a new mock instance.
func NewMockoutputService(ctrl *gomock.Controller) *MockoutputService {
	mock := &MockoutputService{ctrl: ctrl}
	mock.recorder = &MockoutputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutputService) EXPECT() *MockoutputServiceMockRecorder {
	return m.recorder
}

// PrintErrorf mocks base method.
func (m *MockoutputService) PrintErrorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PrintErrorf", varargs...)
}

// PrintErrorf indicates an expected call of PrintErrorf.
func (mr *MockoutputServiceMockRecorder) PrintErrorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintErrorf", reflect.TypeOf((*MockoutputService)(nil).PrintErrorf), varargs...)
}

// PrintOperation mocks base method.
func (m *MockoutputService) PrintOperation(operationType, relativePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintOperation", operationType, relativePath)
}

// PrintOperation indicates an expected call of PrintOperation.
func (mr *MockoutputServiceMockRecorder) PrintOperation(operationType, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOperation", reflect.TypeOf((*MockoutputService)(nil).PrintOperation), operationType, relativePath)
}

// PrintOperationWithTarget mocks base method.
func (m *MockoutputService) PrintOperationWithTarget(operationType, relativePath, target string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintOperationWithTarget", operationType, relativePath, target)
}

// PrintOperationWithTarget indicates an expected call of PrintOperationWithTarget.
func (mr *MockoutputServiceMockRecorder) PrintOperationWithTarget(operationType, relativePath, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOperationWithTarget", reflect.TypeOf((*MockoutputService)(nil).PrintOperationWithTarget), operationType, relativePath, target)
}

// MockfileOps is a mock of fileOps interface.
type MockfileOps struct {
	ctrl     *gomock.Controller
	recorder *MockfileOpsMockRecorder
	isgomock struct{}
}

// MockfileOpsMockRecorder is the mock recorder for MockfileOps.
type MockfileOpsMockRecorder struct {
	mock *MockfileOps
}

// NewMockfileOps creates a new mock instance.
func NewMockfileOps(ctrl *gomock.Controller) *MockfileOps {
	mock := &MockfileOps{ctrl: ctrl}
	mock.recorder = &MockfileOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileOps) EXPECT() *MockfileOpsMockRecorder {
	return m.recorder
}

// CopyFile mocks base method.
func (m *MockfileOps) CopyFile(srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockfileOpsMockRecorder) CopyFile(srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockfileOps)(nil).CopyFile), srcPath, dstPath)
}

// FileExists mocks base method.
func (m *MockfileOps) FileExists(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockfileOpsMockRecorder) FileExists(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockfileOps)(nil).FileExists), filePath)
}

// FindAllFiles mocks base method.
func (m *MockfileOps) FindAllFiles(dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFiles", dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFiles indicates an expected call of FindAllFiles.
func (mr *MockfileOpsMockRecorder) FindAllFiles(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFiles", reflect.TypeOf((*MockfileOps)(nil).FindAllFiles), dir)
}

// ReadFileNormalized mocks base method.
func (m *MockfileOps) ReadFileNormalized(filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNormalized", filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNormalized indicates an expected call of ReadFileNormalized.
func (mr *MockfileOpsMockRecorder) ReadFileNormalized(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNormalized", reflect.TypeOf((*MockfileOps)(nil).ReadFileNormalized), filePath)
}

// RemoveFile mocks base method.
func (m *MockfileOps) RemoveFile(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockfileOpsMockRecorder) RemoveFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockfileOps)(nil).RemoveFile), filePath)
}

// WriteFile mocks base method.
func (m *MockfileOps) WriteFile(filePath, content string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filePath, content, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockfileOpsMockRecorder) WriteFile(filePath, content, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockfileOps)(nil).WriteFile), filePath, content, perm)
}

// MockpathUtils is a mock of pathUtils interface.
type MockpathUtils struct {
	ctrl     *gomock.Controller
	recorder *MockpathUtilsMockRecorder
	isgomock struct{}
}

// MockpathUtilsMockRecorder is the mock recorder for MockpathUtils.
type MockpathUtilsMockRecorder struct {
	mock *MockpathUtils
}

// NewMockpathUtils creates a new mock instance.
func NewMockpathUtils(ctrl *gomock.Controller) *MockpathUtils {
	mock := &MockpathUtils{ctrl: ctrl}
	mock.recorder = &MockpathUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpathUtils) EXPECT() *MockpathUtilsMockRecorder {
	return m.recorder
}

// GetBaseName mocks base method.
func (m *MockpathUtils) GetBaseName(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseName", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseName indicates an expected call of GetBaseName.
func (mr *MockpathUtilsMockRecorder) GetBaseName(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseName", reflect.TypeOf((*MockpathUtils)(nil).GetBaseName), filePath)
}

// GetDirectory mocks base method.
func (m *MockpathUtils) GetDirectory(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectory", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDirectory indicates an expected call of GetDirectory.
func (mr *MockpathUtilsMockRecorder) GetDirectory(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectory", reflect.TypeOf((*MockpathUtils)(nil).GetDirectory), filePath)
}

// GetRelativePath mocks base method.
func (m *MockpathUtils) GetRelativePath(filePath, baseDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelativePath", filePath, baseDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativePath indicates an expected call of GetRelativePath.
func (mr *MockpathUtilsMockRecorder) GetRelativePath(filePath, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativePath", reflect.TypeOf((*MockpathUtils)(nil).GetRelativePath), filePath, baseDir)
}

// NormalizePath mocks base method.
func (m *MockpathUtils) NormalizePath(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizePath", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// NormalizePath indicates an expected call of NormalizePath.
func (mr *MockpathUtilsMockRecorder) NormalizePath(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizePath", reflect.TypeOf((*MockpathUtils)(nil).NormalizePath), filePath)
}

// RecreateDirectoryStructure mocks base method.
func (m *MockpathUtils) RecreateDirectoryStructure(srcPath, srcBase, dstBase string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateDirectoryStructure", srcPath, srcBase, dstBase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecreateDirectoryStructure indicates an expected call of RecreateDirectoryStructure.
func (mr *MockpathUtilsMockRecorder) RecreateDirectoryStructure(srcPath, srcBase, dstBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateDirectoryStructure", reflect.TypeOf((*MockpathUtils)(nil).RecreateDirectoryStructure), srcPath, srcBase, dstBase)
}

// MockgitOps is a mock of gitOps interface.
type MockgitOps struct {
	ctrl     *gomock.Controller
	recorder *MockgitOpsMockRecorder
	isgomock struct{}
}

// MockgitOpsMockRecorder is the mock recorder for MockgitOps.
type MockgitOpsMockRecorder struct {
	mock *MockgitOps
}

// NewMockgitOps creates a new mock instance.
func NewMockgitOps(ctrl *gomock.Controller) *MockgitOps {
	mock := &MockgitOps{ctrl: ctrl}
	mock.recorder = &MockgitOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgitOps) EXPECT() *MockgitOpsMockRecorder {
	return m.recorder
}

// CommitChanges mocks base method.
func (m *MockgitOps) CommitChanges(repoDir, commitMessage string, withoutPush bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitChanges", repoDir, commitMessage, withoutPush)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitChanges indicates an expected call of CommitChanges.
func (mr *MockgitOpsMockRecorder) CommitChanges(repoDir, commitMessage, withoutPush any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitChanges", reflect.TypeOf((*MockgitOps)(nil).CommitChanges), repoDir, commitMessage, withoutPush)
}

// GetGitRootDir mocks base method.
func (m *MockgitOps) GetGitRootDir(startDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitRootDir", startDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitRootDir indicates an expected call of GetGitRootDir.
func (mr *MockgitOpsMockRecorder) GetGitRootDir(startDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitRootDir", reflect.TypeOf((*MockgitOps)(nil).GetGitRootDir), startDir)
}

// MockfileFilter is a mock of fileFilter interface.
type MockfileFilter struct {
	ctrl     *gomock.Controller
	recorder *MockfileFilterMockRecorder
	isgomock struct{}
}

// MockfileFilterMockRecorder is the mock recorder for MockfileFilter.
type MockfileFilterMockRecorder struct {
	mock *MockfileFilter
}

// NewMockfileFilter creates a new mock instance.
func NewMockfileFilter(ctrl *gomock.Controller) *MockfileFilter {
	mock := &MockfileFilter{ctrl: ctrl}
	mock.recorder = &MockfileFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileFilter) EXPECT() *MockfileFilterMockRecorder {
	return m.recorder
}

// CleanupExtraFilesByPatterns mocks base method.
func (m *MockfileFilter) CleanupExtraFilesByPatterns(srcFiles []string, srcBase, dstBase string, patterns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExtraFilesByPatterns", srcFiles, srcBase, dstBase, patterns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExtraFilesByPatterns indicates an expected call of CleanupExtraFilesByPatterns.
func (mr *MockfileFilterMockRecorder) CleanupExtraFilesByPatterns(srcFiles, srcBase, dstBase, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExtraFilesByPatterns", reflect.TypeOf((*MockfileFilter)(nil).CleanupExtraFilesByPatterns), srcFiles, srcBase, dstBase, patterns)
}

// FindFilesByPatterns mocks base method.
func (m *MockfileFilter) FindFilesByPatterns(dir string, patterns []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilesByPatterns", dir, patterns)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilesByPatterns indicates an expected call of FindFilesByPatterns.
func (mr *MockfileFilterMockRecorder) FindFilesByPatterns(dir, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilesByPatterns", reflect.TypeOf((*MockfileFilter)(nil).FindFilesByPatterns), dir, patterns)
}

// GetEffectivePatterns mocks base method.
func (m *MockfileFilter) GetEffectivePatterns(patterns []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectivePatterns", patterns)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetEffectivePatterns indicates an expected call of GetEffectivePatterns.
func (mr *MockfileFilterMockRecorder) GetEffectivePatterns(patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectivePatterns", reflect.TypeOf((*MockfileFilter)(nil).GetEffectivePatterns), patterns)
}

// GetFilePatterns mocks base method.
func (m *MockfileFilter) GetFilePatterns(flagValue, envVarName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePatterns", flagValue, envVarName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePatterns indicates an expected call of GetFilePatterns.
func (mr *MockfileFilterMockRecorder) GetFilePatterns(flagValue, envVarName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePatterns", reflect.TypeOf((*MockfileFilter)(nil).GetFilePatterns), flagValue, envVarName)
}
